import os
import sqlite3
from datetime import date, timedelta

import psycopg

import config

_postgres_initialised = False


def connection_open(app):
    if config.DEMO_MODE:
        os.makedirs(os.path.dirname(config.SQLITE_PATH), exist_ok=True)
        connection = sqlite3.connect(
            config.SQLITE_PATH,
            detect_types=sqlite3.PARSE_DECLTYPES | sqlite3.PARSE_COLNAMES,
        )
        connection.execute('PRAGMA foreign_keys = ON')
        _initialise_demo_database(connection)
        return connection

    if config.DATABASE_URL:
        connection = psycopg.connect(config.DATABASE_URL)
    else:
        connection = psycopg.connect(
            host=config.PG_HOST,
            port=config.PG_PORT,
            user=config.PG_USER,
            password=config.PG_PASSWORD,
            dbname=config.PG_DATABASE,
            sslmode=config.PG_SSLMODE,
        )
    _initialise_postgres_database(connection)
    return connection


def _initialise_demo_database(connection):
    connection.executescript('''
        CREATE TABLE IF NOT EXISTS user_table (
            email TEXT PRIMARY KEY, password TEXT NOT NULL, first_name TEXT NOT NULL,
            last_name TEXT NOT NULL, medical_info TEXT, user_role TEXT DEFAULT 'user'
        );
        CREATE TABLE IF NOT EXISTS event_table (
            event_id INTEGER PRIMARY KEY AUTOINCREMENT, event_name TEXT NOT NULL,
            date DATE NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL,
            category TEXT, capacity INTEGER NOT NULL, location TEXT, location_link TEXT,
            event_topic TEXT, event_coach TEXT
        );
        CREATE TABLE IF NOT EXISTS sign_up_log (
            sign_up_id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL,
            event_id INTEGER NOT NULL, timestamp DATETIME NOT NULL,
            booked_gi INTEGER DEFAULT 0,
            UNIQUE(email, event_id),
            FOREIGN KEY(email) REFERENCES user_table(email),
            FOREIGN KEY(event_id) REFERENCES event_table(event_id)
        );
    ''')
    if connection.execute('SELECT COUNT(*) FROM event_table').fetchone()[0] == 0:
        demo_date = date.today() + timedelta(days=7)
        connection.execute('''
            INSERT INTO event_table
            (event_name, date, start_time, end_time, category, capacity, location,
             location_link, event_topic, event_coach)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', ('Demo taster session', demo_date, '18:00:00', '20:00:00', 'Nogi', 30,
              'UoB Sport & Fitness Centre', 'https://www.birmingham.ac.uk/',
              'Introduction to Brazilian jiu-jitsu', 'Demo coach'))
    connection.commit()


def _initialise_postgres_database(connection):
    global _postgres_initialised
    if _postgres_initialised:
        return
    with connection.cursor() as cursor:
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS user_table (
                email TEXT PRIMARY KEY, password TEXT NOT NULL, first_name TEXT NOT NULL,
                last_name TEXT NOT NULL, medical_info TEXT, user_role TEXT DEFAULT 'user'
            );
            CREATE TABLE IF NOT EXISTS event_table (
                event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                event_name TEXT NOT NULL, date DATE NOT NULL, start_time TIME NOT NULL,
                end_time TIME NOT NULL, category TEXT, capacity INTEGER NOT NULL,
                location TEXT, location_link TEXT, event_topic TEXT, event_coach TEXT
            );
            CREATE TABLE IF NOT EXISTS sign_up_log (
                sign_up_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email TEXT NOT NULL REFERENCES user_table(email),
                event_id INTEGER NOT NULL REFERENCES event_table(event_id),
                timestamp TIMESTAMP NOT NULL, booked_gi BOOLEAN DEFAULT FALSE,
                UNIQUE(email, event_id)
            );
        ''')
    connection.commit()
    _postgres_initialised = True


def _sql(sql):
    return sql.replace('%s', '?') if config.DEMO_MODE else sql


def db_update(app, sql, values):
    connection = None
    cursor = None
    try:
        connection = connection_open(app)
        cursor = connection.cursor()
        cursor.execute(_sql(sql), values)
        connection.commit()
    except (psycopg.Error, sqlite3.Error) as err:
        print(f"Error: {err}")
    finally:
        if cursor:
            cursor.close()
        if connection:
            connection.close()


def db_query(app, sql):
    connection = connection_open(app)
    cursor = connection.cursor()
    try:
        cursor.execute(_sql(sql))
        return cursor.fetchall()
    finally:
        cursor.close()
        connection.close()


def db_query_values(app, sql, values):
    connection = connection_open(app)
    cursor = connection.cursor()
    try:
        cursor.execute(_sql(sql), values)
        return cursor.fetchall()
    finally:
        cursor.close()
        connection.close()
