services:
  - type: web
    name: uob-bjj-webapp
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /healthz
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: uob-bjj-db
          property: connectionString
      - key: DEMO_MODE
        value: "0"
      - key: FLASK_DEBUG
        value: "0"
      - key: PERMANENT_ADMIN_EMAIL
        value: txc282@student.bham.ac.uk
      - key: INITIAL_ADMIN_EMAIL
        sync: false
      - key: INITIAL_ADMIN_PASSWORD
        sync: false
      - key: INITIAL_ADMIN_FIRST_NAME
        sync: false
      - key: INITIAL_ADMIN_LAST_NAME
        sync: false

databases:
  - name: uob-bjj-db
    plan: free
    region: frankfurt
    databaseName: uob_bjj
    user: uob_bjj
    postgresMajorVersion: "16"
